dist: trusty
branches:
  only:
    - master
matrix:
  include:
    - language: crystal
      crystal: latest
      before_script:
        - cd crystal
    - language: python
      python: 3.6
      before_script:
        - cd python
      script:
        - python -m unittest tests.py
    - language: ruby
      ruby: 2.5
      before_script:
        - cd ruby
      script:
        - ruby tests.rb
    - language: rust
      rust: stable
      before_script:
        - cd rust
    - name: nim
      sudo: required
      services:
        - docker
      before_install:
        - docker pull nimlang/nim
      script:
        - cd nim
        - docker run nimlang/nim nim --version
        - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c "nimble install -dy && nimble test"
    - language: scala
      scala: 2.12.5
      before_script:
        - cd scala
    - language: perl6
      perl6: "2018.10"
      before_script:
          - cd perl6
