#!/usr/bin/env python3 -OO

"""Highly divisible triangular number
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be
1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import math

def run(num_factors):
    for num in get_tr_num():
        factors = get_factors(num)
        if len(factors) >= num_factors:
            return num

def get_tr_num():
    idx = 1
    num = 0
    while True:
        num += idx
        idx += 1
        yield num

def get_factors(num):
    factors = []
    for idx in range(1, int(math.sqrt(num))):
        if num % idx == 0:
            factors.append(idx)
            factors.append(num // idx)
    return factors

