#!/usr/bin/env perl6

# even fibonacci numbers
# problem 2
# each new term in the fibonacci sequence is generated by adding the preview two
# terms. by starting with 1 and 2, the first 10 terms will be:
#      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# by considering the terms in the fibonacci sequence whose values do not exceed
# four million, find the sum of the even terms.

sub p002(Int $num where $num > 0) returns Int {
    [+] (1, 2, *+* ...^ * > $num).grep(* %% 2);        
}
