#!/usr/bin/env python3 -OO

"""Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be:

                                    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
"""

def fib(num1, num2):
    return num2, num1 + num2

def run(upto):
    sum = 0
    prev, fib_num = 0, 1
    while fib_num < upto:
        if fib_num % 2 == 0:
            sum += fib_num
        prev, fib_num = fib(prev, fib_num)
    return sum
